plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.example.callandsmsblocker'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.callandsmsblocker"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions { sourceCompatibility JavaVersion.VERSION_11; targetCompatibility JavaVersion.VERSION_11 }
    kotlinOptions { jvmTarget = "11" }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.0"
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    // libphonenumber for phone number parsing
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.13.22'
}
